Repository add-ons/plugin.video.regiotv, pull requests merged in 2020-06, with the labels that each got.

#12 Add IPTV Manager to settings
  resources/language/resource.language.en_gb/strings.po
  resources/settings.xml
Labels: enhancement

#13 Prepare for v0.1.2 release
  README.md
  addon.xml
Labels: release

#14 Fix data transfers over 1 MB to IPTV Manager
  resources/lib/iptvmanager.py
Labels: bug
